module SortedArray;

// An immutable array with the guarantee that its elements are sorted
class .SortedArray<T: frozen & Orderable> private (
  private inner: .Array<T>,
)
  extends .IndexedSequence<T>
  uses
    IntoIterator<T>,
    FromIterator<T>,
    Show[T: Show],
    Hashable[T: Hashable],
    Orderable,
    Equality,
    AsBytes,
   {
  static fun createFromArray(a: Array<T>): this {
    if (a.isSorted()) static(a) else static(a.sorted())
  }
  static fun createFromVector<V: readonly Vector<T>>(v: V): this {
    if (v.isSorted()) static(v.toArray()) else {
      a = Array::mcreateFromItems(v);
      a.sort();
      static(unsafe_chill_trust_me(a))
    }
  }
  static fun createFromItems<I: readonly Sequence<T>>(items: I): this {
    a = Array::mcreateFromItems(items);
    if (a.isSorted()) static(unsafe_chill_trust_me(a)) else static(a.sorted())
  }
  static fun createFromIterator<I: mutable Iterator<T>>(it: I): this {
    v = Vector::mcreateFromIterator(it);
    if (!v.isSorted()) {
      v.sort();
    };
    static(v.toArray())
  }

  fun size(): Int {
    this.inner.size()
  }
  fun values(): mutable Iterator<T> {
    this.inner.values()
  }
  fun chill(): this {
    this
  }
  fun get(index: Int): T {
    this.inner.get(index)
  }
  fun ==<U: Orderable>[T: U](other: SortedArray<U>): Bool {
    this.inner == other.inner
  }
  fun toString[T: Show](): String {
    this.inner.toString()
  }
  fun bytes(): readonly Bytes {
    this.inner.bytes()
  }
}

private fun byKey<K: frozen, V>(kv: (K, V)): K {
  kv.i0
}

class .SortedKVArray<K: frozen & Orderable, V> private (
  private inner: .Array<(K, V)>,
)
  extends .Sequence<(K, V)>
  uses
    IntoIterator<(K, V)>,
    FromIterator<(K, V)>,
    Show[K: Show, V: Show],
    Hashable[K: Hashable, V: Hashable],
    Orderable[V: Orderable],
    Equality[V: Equality],
   {
  static fun createFromArray(a: Array<(K, V)>): this {
    if (a.isSortedBy(byKey)) static(a) else static(a.sortedBy(byKey))
  }
  static fun createFromVector<V: readonly Vector<(K, V)>>(v: V): this {
    if (v.isSortedBy(byKey)) static(v.toArray()) else {
      a = Array::mcreateFromItems(v);
      a.sortBy(byKey);
      static(unsafe_chill_trust_me(a))
    }
  }
  static fun createFromItems<I: readonly Sequence<(K, V)>>(items: I): this {
    a = Array::mcreateFromItems(items);
    if (a.isSortedBy(byKey)) static(unsafe_chill_trust_me(a)) else {
      static(a.sortedBy(byKey))
    }
  }
  static fun createFromIterator<I: mutable Iterator<(K, V)>>(it: I): this {
    v = Vector::mcreateFromIterator(it);
    if (!v.isSortedBy(byKey)) {
      v.sortBy(byKey)
    };
    static(v.toArray())
  }

  fun size(): Int {
    this.inner.size()
  }
  fun values(): mutable Iterator<(K, V)> {
    this.inner.values()
  }
  fun chill(): this {
    static(this.inner.chill())
  }
  fun get(index: Int): (K, V) {
    this.inner.get(index)
  }
  fun ==<K2: Orderable, V2: Orderable>[K: K2, V: V2](
    other: SortedKVArray<K2, V2>,
  ): Bool {
    this.inner == other.inner
  }
  fun toString[K: Show, V: Show](): String {
    this.inner.toString()
  }
}

module end;
