fun main(): void {
  print_raw(0.0.nextAfter(-1.0).toString() + "\n");
  print_raw(0.0.nextAfter(0.0).toString() + "\n");
  print_raw(0.0.nextAfter(1.0).toString() + "\n");
  print_raw(0.0.nextAfter(Float::nan).toString() + "\n");
  print_raw(1.0.nextAfter(-1.0).toString() + "\n");
  print_raw(1.0.nextAfter(0.0).toString() + "\n");
  print_raw(1.0.nextAfter(1.0).toString() + "\n");
  print_raw(1.0.nextAfter(Float::nan).toString() + "\n");
  print_raw(Float::nan.nextAfter(-1.0).toString() + "\n");
  print_raw(Float::nan.nextAfter(0.0).toString() + "\n");
  print_raw(Float::nan.nextAfter(1.0).toString() + "\n");
}
