module Cli;

base class Arg{name:String,
  _short: ?String = None(),
  _long: ?String = None(),
  _about: ?String = None(),
  _global: Bool = false,
  _env: ?String = None(),
  _positional: Bool = false
  } {
  // Builder interface methods.
  fun short(flag: String): this {
    this with {_short => Some(flag)}
  }

  fun long(flag: String): this {
    this with {_long => Some(flag)}
  }

  fun about(msg: String): this {
    this with {_about => Some(msg)}
  }

  fun global(): this {
    this with {_global => true}
  }

  overridable fun env(name: String): this {
    this with {_env => Some(name)}
  }

  fun positional(value: Bool = true): this {
    this with {_positional => value}
  }

  overridable fun isNegatable(): Bool {
    false
  }
  overridable fun isRequired(): Bool {
    false
  }
  fun getDefault(): ?Value;

  static fun string(name:String): StringArg {
    StringArg{name, valConstructor => v ~> StringValue(v)}
  }
  static fun int(name:String): IntArg {
    IntArg{name, valConstructor => v ~> IntValue(v)}
  }
  static fun bool(name:String): BoolArg {
    BoolArg{name, valConstructor => v ~> BoolValue(v)}
  }
  static fun array(name:String):ArrayArg {
    ArrayArg{name, valConstructor => v ~> ArrayValue(v)}
  }
}

base class TypedArg<T:frozen>{
  // NOTE: The following parameters cannot be placed in subclasses, since `name` is required.
  // Other than BoolArgs only
  _default: ?T = None(),
  _required: Bool = false,
  valConstructor : T ~> TypedValue<T>
} extends Arg {
  fun default(value : T): this {
    this with {_default => Some(value)}
  }
  fun baseDefault(): TypedValue<T>;
  fun mkVal(possibleValue:?T): TypedValue<T> {
    possibleValue.bind(this._default).map(this.valConstructor).default(this.baseDefault())
  }
  fun getDefault(): ?Value {
    this._default.map(this.valConstructor)
  }
}

base class ValuedArg<T:frozen> extends TypedArg<T> {
  fun baseDefault(): TypedValue<T> { MissingValue() }
  fun required(value: Bool = true): this {
    this with {_required => value}
  }

  fun isRequired(): Bool { this._required }
}

class StringArg extends ValuedArg<String> { }

class IntArg extends ValuedArg<Int> { }

class ArrayArg extends ValuedArg<Array<String>> {
  fun env(_name: String): this {
    invariant_violation("TODO")
  }
}

class BoolArg{_negatable: Bool = false} extends TypedArg<Bool> {
  fun baseDefault(): TypedValue<Bool> { BoolValue(false) }
  fun negatable(value: Bool = true): this {
    this with {_negatable => value}
  }

  fun isNegatable(): Bool { this._negatable }
}

class Command(
  name: String = "",
  _args: Array<Arg> = Array[],
  _extra: Bool = false,
  _extraName: ?String = None(),
  _subcommands: Array<Command> = Array[],
  _about: ?String = None(),
  _short: ?String = None(),
) {
  fun arg(arg: Arg): this {
    this with {_args => this._args.concat(Array[arg])}
  }

  fun extra(name: String = ""): this {
    this with {
      _extra => true,
      _extraName => if (name != "") Some(name) else None(),
    }
  }

  fun subcommand(cmd: Command): this {
    this with {_subcommands => this._subcommands.concat(Array[cmd])}
  }

  fun about(msg: String): this {
    this with {_about => Some(msg)}
  }

  fun short(n: String): this {
    this with {_short => Some(n)}
  }

  fun help(): this {
    this.arg(
      Cli.Arg::bool("help")
        .short("h")
        .long("help")
        .about("Print help information")
        .global(),
    )
  }

  fun parseArgs(): ParseResults {
    res = parseArgs(this);

    if (res.values.containsKey("help") && res.getBool("help")) {
      res.subcommand match {
      | Some(subcmd) ->
        this._subcommands.find(c -> c.name == subcmd) match {
        | Some(cmd) -> print_string(usage(cmd, true, Some(this)))
        | None() -> invariant_violation(`Unknown subcommand ${subcmd}`)
        }
      | None() -> print_string(usage(this, true))
      };
      skipExit(0)
    };

    res.error.each(err -> {
      print_error(`error: ${err.getMessage()}\n`);
      res.subcommand match {
      | Some(subcmd) ->
        this._subcommands.find(c -> c.name == subcmd) match {
        | Some(cmd) -> print_error(usage(cmd, false, Some(this)))
        | None() -> invariant_violation(`Unknown subcommand ${subcmd}`)
        }
      | None() -> print_error(usage(this, false))
      };
      skipExit(1)
    });

    res
  }
}

module end;
